[feat] forces utxos
go-faast/coin-payments pull request #125
Opened 2020-11-02 18:45 UTC by dzdidi

2020-11-03 00:46 UTC, dylanseago requested changes

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      if (!tbc.useUnconfirmedUtxos && !isConfirmedUtxo(utxo)) {
This filter is dangerous because it could result in no enforced utxos being used and cause a double spend. But if a check is added to ensure at least one of them is used it should be safe. My latest understanding is that only one is required for it to be considered a valid replacement.

One potentially useful application of this filter is allowing us to RBF a transaction that for whatever reason included a malicious output that will never confirm. Some spammers create huge chains of very low fee transactions that spend their own unconfirmed outputs causing them to be stuck in the mempool indefinitely. With this logic we could recover with RBF because the legit confirmed inputs would be included and the unconfirmed spam one would be excluded.

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        : toBigNumber(utxo.satoshis).toNumber()
I see these 3 lines used in multiple places. I'd suggest calculating the satoshi value for all UTXOs right at the beginning, just like it's being done for the outputs, or adding a helper function

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    tbc.isSweep = tbc.useAllUtxos && tbc.desiredOutputTotal >= tbc.inputTotal
This will always be false due this condition
https://github.com/go-faast/coin-payments/pull/125/files#diff-69cd949b31746a127fdbe1a40819250617c1016a9d4fe0782aed5e27bcf7f8d9R336

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      tbc.enforcedUtxos.length,
Since `unusedUtxos` will never include `enforcedUtxos` the correct call here would be `this.determineTargetChangeOutputCount(tbc.unusedUtxos.length, 0)`

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    const feeSat = this.estimateTxFee(
This value is exactly the same as `idealSolutionFeeSat`

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      return
I believe a call to `adjustTxFee` is missing before returning here

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      tbc.enforcedUtxos.length,
This should be `tbc.inputUtxos.length` given that this filter exists
https://github.com/go-faast/coin-payments/pull/125/files#diff-69cd949b31746a127fdbe1a40819250617c1016a9d4fe0782aed5e27bcf7f8d9R375

2020-11-03 00:46 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    let selectedTotalSat = tbc.enforcedUtxos.reduce((total, { satoshis }) => total.plus(satoshis || 0), new BigNumber(0))
Same as previous comment, should be `tbc.inputUtxos.reduce`

2020-11-03 09:28 UTC, dzdidi commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        : toBigNumber(utxo.satoshis).toNumber()
How about forcing `utxo.value` to be in base denomination (statoshis) and not having the `utxo.satoshi?` at all?

2020-11-03 19:14 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        : toBigNumber(utxo.satoshis).toNumber()
In general, all values across coin-payments are main denomination strings for consistency. Adding satoshi is just for convenience within buildPaymentTx to avoid the need for BigNumber. Changing that now could break backwards compatibility depending on what you're suggesting

2020-11-03 21:03 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +      throw new Error('Failed to create replacement tx: Potential doublspend of utxos.')
Regarding wording of error messages: This message is a bit too alarmist. If a tx failed and support saw this they could think we actually double spent and elevate the issue when in reality nothing happened. Consider this instead:
`${this.coinSymbol} buildPaymentTx - Failed to create replacement tx: all enforced utxos are unconfirmed`

2020-11-04 17:05 UTC, dylanseago requested changes

2020-11-04 17:19 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    const currentBlock = await this._retryDced(() => this.getBlock())
`getBlock` actually returns details for all transactions included in the block and is not the best way to get current block height.

There's another much cheaper option: `(await this.getApi().getStatus()).blockbook.bestHeight`

2020-11-04 17:52 UTC, dzdidi commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        tbc.inputTotal += utxo.satoshis as number
yes but TS error is about `string | number`

2020-11-04 18:20 UTC, dzdidi commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        tbc.inputTotal += utxo.satoshis as number
it is not because of null but `number | string`

2020-11-04 19:32 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +        tbc.inputTotal += utxo.satoshis as number
Ah, my bad. Makes sense

2020-11-04 20:59 UTC, dylanseago requested changes

2020-11-04 20:59 UTC, dylanseago commented on packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> +    const utxoSpendCost = this.estimateTxFee(params.desiredFeeRate, 0, 0, [])
This should be:
`this.estimateTxFee(params.desiredFeeRate, 1, 0, []) - this.estimateTxFee(params.desiredFeeRate, 0, 0, [])`
(fee of header + 1 input) - (fee of header)

Also logging this would be useful:
````
this.logger.log(`${this.coinSymbol} buildPaymentTx - Ignoring utxos of ${utxoSpendCost} sat or lower`)
````

2020-11-05 20:59 UTC, dylanseago approved these changes

2020-11-06 12:18 UTC, merged